version: "3.9"
services:
  app:
    image: my_app:latest
    volumes:
      - ./:/app
    networks:
      - mysql-python-app-network
  mysql-flask-app-container:
    image: mysql:8.0.28
    container_name: mysql-flask-app-container
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-python-app-volume:/var/lib/mysql
      - mysql-python-app-volume-config:/etc/mysql
    networks:
      - mysql-python-app-network
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - mysql-python-app-network
volumes:
  mysql-python-app-volume:
  mysql-python-app-volume-config:
networks:
  mysql-python-app-network:
    name: mysql-python-app-network